import Foundation

let now = Date(timeIntervalSince1970: 1000)
var timer = Countdown()
timer.start(seconds: 60, at: now)
assert(timer.remaining(at: now.addingTimeInterval(10)) == 50)
timer.pause(at: now.addingTimeInterval(10))
assert(timer.remaining(at: now.addingTimeInterval(100)) == 50)
timer.resume(at: now.addingTimeInterval(100))
assert(!timer.finishIfDue(at: now.addingTimeInterval(149)))
assert(timer.finishIfDue(at: now.addingTimeInterval(150)))
assert(!timer.finishIfDue(at: now.addingTimeInterval(151)))
timer.start(seconds: 60, at: now)
assert(timer.finishIfDue(at: now.addingTimeInterval(3600))) // wake after sleep
timer.start(seconds: 120, at: now)
let data = try JSONEncoder().encode(timer)
var restored = try JSONDecoder().decode(Countdown.self, from: data)
assert(restored.remaining(at: now.addingTimeInterval(20)) == 100)
restored.reset()
assert(!restored.isRunning && !restored.isPaused && restored.duration == 120)
assert(Countdown.display(59.1) == "01:00")
assert(Countdown.display(-1) == "00:00")
assert(Countdown.display(599 * 60) == "599:00")
print("通过：倒计时、暂停、继续、到期仅触发一次、睡眠后到期、状态恢复、重置、时间显示")

var log = ActivityLog()
log.begin(task: "Test task", category: "学习", at: now)
log.finish(at: now.addingTimeInterval(60), reason: "暂停")
log.begin(task: "Test task", category: "学习", at: now.addingTimeInterval(120))
log.checkpoint(at: now.addingTimeInterval(150))
log.recover()
assert(log.entries.reduce(0) { $0 + $1.seconds } == 90)
assert(log.active == nil)
let span = DateInterval(start: now.addingTimeInterval(30), end: now.addingTimeInterval(130))
assert(log.entries.reduce(0) { $0 + $1.seconds(in: span) } == 40)
assert(!log.addManual(Activity(task: "Overlap", category: "其他", start: now, end: now.addingTimeInterval(40), reason: "manual"), now: now.addingTimeInterval(200)))
assert(log.addManual(Activity(task: "Other", category: "其他", start: now.addingTimeInterval(60), end: now.addingTimeInterval(120), reason: "manual"), now: now.addingTimeInterval(200)))
let roundTrip = try JSONDecoder().decode(ActivityLog.self, from: JSONEncoder().encode(log))
assert(roundTrip.entries.count == 3)
print("PASS: activity segments, pause exclusion, crash recovery, interval clipping, overlap rejection, persistence")

let valid = ActivityImport(version: 1, source: "ai", entries: [.init(task: "AI example", category: "工作", start: now.addingTimeInterval(150), end: now.addingTimeInterval(180))])
let imported = try valid.applying(to: log, now: now.addingTimeInterval(200))
assert(imported.entries.count == log.entries.count + 1 && imported.entries.last!.reason == "AI补记")
let duplicate = ActivityImport(version: 1, source: "ai", entries: valid.entries + valid.entries)
do { _ = try duplicate.applying(to: log, now: now.addingTimeInterval(200)); assertionFailure("Overlap accepted") } catch {}
assert(log.entries.count == 3)
let gaps = log.gaps(in: DateInterval(start: now, end: now.addingTimeInterval(200)), now: now.addingTimeInterval(200))
assert(gaps.count == 1 && gaps[0].duration == 50)
print("PASS: AI import validation, atomic rejection and unrecorded interval API")
