import Foundation

let now = Date(timeIntervalSince1970: 1000)
var timer = Countdown()
timer.start(seconds: 60, at: now)
assert(timer.remaining(at: now.addingTimeInterval(10)) == 50)
timer.pause(at: now.addingTimeInterval(10))
assert(timer.remaining(at: now.addingTimeInterval(100)) == 50)
timer.resume(at: now.addingTimeInterval(100))
assert(!timer.finishIfDue(at: now.addingTimeInterval(149)))
assert(timer.finishIfDue(at: now.addingTimeInterval(150)))
assert(!timer.finishIfDue(at: now.addingTimeInterval(151)))
timer.start(seconds: 60, at: now)
assert(timer.finishIfDue(at: now.addingTimeInterval(3600))) // wake after sleep
timer.start(seconds: 120, at: now)
let data = try JSONEncoder().encode(timer)
var restored = try JSONDecoder().decode(Countdown.self, from: data)
assert(restored.remaining(at: now.addingTimeInterval(20)) == 100)
restored.reset()
assert(!restored.isRunning && !restored.isPaused && restored.duration == 120)
assert(Countdown.display(59.1) == "01:00")
assert(Countdown.display(-1) == "00:00")
assert(Countdown.display(599 * 60) == "599:00")
print("通过：倒计时、暂停、继续、到期仅触发一次、睡眠后到期、状态恢复、重置、时间显示")
